### PR TITLE
Allow override of filename

### LINKED ISSUE #164: Add possibility to map project keys to custom names
Instead of a file with an autoname based on project key (like EX.org or AHU.org) we want to have a user customizable prefix or some type of override map, so you may define:

    (("EX" . "your-file-name") ("AHU" . "your-other-name"))

See also #79

### PR DESCRIPTION
**Pull request by Fuco1**
Fix #164

### CODE REVIEW

**Comment by ahungry** [comment]
Conflict with your other PR

**Comment by Fuco1** [comment]
@ahungry I've fixed the conflicts and rebased on top of master.

**Comment by ahungry** [comment]
Nice, thanks!

**Comment by Fuco1** [comment]
@ahungry While we're talking about specifying targets, a really cool feature would also be to be able to specify the heading with an ID (see `org-id-get-create`) so I can point org-jira to any file and any headline I want: and then it should update that tree with the jira data.

For example I actually have a file `work.org` where I have all the clients except the one using jira which now syncs into a separate file.  This is quite inconvenient when working with clock reports and similar org-mode tools.

Org mode has facilities to give you back a marker for an ID so it should be very easy to get the point to the correct buffer/file/heading.

**Comment by ahungry** [comment]
I just added the custom-jql branch, it adds  a new "filename" attribute to the org data, so most (should be all) commands that operate on an issue will now map correctly to an issue, regardless of what file it is located in, as long as it has a filename attribute properly set to match it's containing filename (this will be auto-set on all new WRITE commands).

**Pull request merged**
