### PR TITLE
Allow additional content before the first headline to exist.

### LINKED ISSUE #167: Do not require the "%s-Tickets" to be the first line in the file
the code in the rendering function 

```elisp
          (goto-char (point-min))
          (unless (looking-at (format "^* %s-Tickets" proj-key))
            (insert (format "* %s-Tickets\n" proj-key))
```

breaks features like custom org headers, for example

```org
#+FILETAGS: WORK
```

Can we relax this a bit and instead search for the first headline being that?

Ideally later we could specify target headlines but this would already be pretty sweet.  I would also like to put clock reports on the top of the file and they get broken because of this.

Also the check should be relaxed and allow for a TODO state keyword.  For example I  need the task to be marked TODO in order for my project queries to work.

We can use `org-element-at-point`

```
(headline
 (:raw-value "SC-Tickets" :begin 30 :end 24718 :pre-blank 0 :contents-begin 48 :contents-end 24718 :level 1 :priority nil :tags nil :todo-keyword
  #("TODO" 0 4
    (fontified t org-category "saleschamp" face
               (:foreground "IndianRed1" :weight bold)
               :org-clock-minutes 19))
  :todo-type todo :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 30 :TOGGL-PROJECT "Budget Energie" :title "SC-Tickets"))
```

and then look at the `:title` property.

I can do the patch if you are interested.  I will do this anyway for my fork though... so I might just as well submit it.

### PR DESCRIPTION
**Pull request by Fuco1**
Useful for file tags or clock-reports.

Fixes #167

### CODE REVIEW

**Comment by ahungry** [comment]
Do we need with this from around 9 days ago?

f3350c5c

I think we were handling the same problem again :smile:  (in either case, merge conflict atm)

**Comment by ahungry** [comment]
If your solution is preferred, can you please let me know what use cases it solves for that the other one does not?

**Comment by ahungry** [comment]
Sorry, I just realized I may have taken that long to slowly finish the custom JQL branch and this commit might not have existed until then.

The "maybe" render is needed to support the custom JQL stuff (a project file can now have multiple top-level headings in it vs one project per file).  It should also in theory avoid mangling meta-data at top of file.

I'll run the test on that to confirm and adjust based on your PR if not.

**Comment by Fuco1** [comment]
Yes your patch seem to handle it except it doesn't allow for a TODO keyword.  See the inline comments.

**Pull request merged**
