### PR TITLE
Render display names in comments

### PR DESCRIPTION
**Pull request by cartesian-theatrics**
See #221. My elisp skills are severely lacking, so probably would need cleanup. Still need to implement inserting mentions in comments.

### CODE REVIEW

**Comment by ahungry** [comment]
Thanks for the PR!  There have been some other changes merged in since this was made.

Do you know if it is still needed?  If so, does it work well with the other changes?

**Comment by ahungry** [comment]
@cartesian-theatrics not sure if you're still interested in this PR - in any case, how does add-text-properties work?  Does it only render the display name value on the first render or is it altering the contents in the org file?

If it alters the contents in the org file, when the data is synced back to Jira, what happens?  Does the display name retain the name link association on the Jira system or does it lose it? (is the data-sync two way?)

**Comment by cartesian-theatrics** [comment]
Hi @ahungry, add-text-properties basically adds meta-data to strings that emacs picks up as the text to render rather than the string itself. However, the result of serialization *should* be the same. The code as is unfortunately has the issue that it doesn't render mentions correction innitially, you have to run `org-jira-update-issue`. I'm sure it's an easy fix, but I haven't looked into it much. I'd want to fix that at least before merging.

**Comment by ahungry** [comment]
Closing due to inactivity.

**Pull request closed without merging**
